WebFitness/Areas/Admin/Controllers/TipoExercicioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFitness.Classes;

namespace WebFitness.Areas.Admin.Controllers
{
    public class TipoExercicioController : Controller
    {
        private WebfitnessDBEntities db = new WebfitnessDBEntities();
        private String controller = "Tipo Exercício";

        //
        // GET: /Admin/TipoEquipamento/
        [Authorize]
        public ActionResult Index()
        {
            @ViewBag.Controller = controller;
            return View(db.TpExercicio.ToList());
        }

        //
        // GET: /Admin/TipoEquipamento/Create
        [Authorize]
        public ActionResult Create()
        {
            @ViewBag.Controller = controller;
            return View();
        }

        //
        // POST: /Admin/TipoEquipamento/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TpExercicio tpexercicio)
        {
            @ViewBag.Controller = controller;

            tpexercicio.dtCriacao = DateTime.Now;
            tpexercicio.status = (byte) Status.Ativo;
            tpexercicio.idTpExercicio = 1;
            tpexercicio.dsTpExercicio = Validation.SyntaxName(tpexercicio.dsTpExercicio);

            if (ModelState.IsValid)
            {
                db.TpExercicio.Add(tpexercicio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tpexercicio);
        }
        
        //
        // GET: /Admin/TipoEquipamento/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            @ViewBag.Controller = controller;
            TpExercicio tpexercicio = db.TpExercicio.Find(id);
            if (tpexercicio == null)
            {
                return HttpNotFound();
            }
            return View(tpexercicio);
        }

        //
        // POST: /Admin/TipoEquipamento/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TpExercicio tpexercicio)
        {
            @ViewBag.Controller = controller;
            tpexercicio.dsTpExercicio = Validation.SyntaxName(tpexercicio.dsTpExercicio);
            if (ModelState.IsValid)
            {
                db.Entry(tpexercicio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tpexercicio);
        }

        //
        // GET: /Admin/TipoEquipamento/Inactive/5
        [Authorize]
        public ActionResult Inactive(int id = 0)
        {
            @ViewBag.Controller = controller;

            TpExercicio tpexercicio = db.TpExercicio.Find(id);

            if (tpexercicio == null)
            {
                return HttpNotFound();
            }
            tpexercicio.status = (byte) Status.Inativo;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Admin/TipoEquipamento/Active/5
        [Authorize]
        public ActionResult Active(int id = 0)
        {
            @ViewBag.Controller = controller;

            TpExercicio tpexercicio = db.TpExercicio.Find(id);

            if (tpexercicio == null)
            {
                return HttpNotFound();
            }
            tpexercicio.status = (byte) Status.Ativo;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebFitness/Areas/Admin/Views/TipoExercicio/Create.cshtml
@model WebFitness.TpExercicio

@{
    ViewBag.Title = "Cadastrar";
}

<div class="span7">
    <div class="top-bar">
        <h3>
            <i class="icon-cog"></i>
            Cadastro de Tipo de Exercício
        </h3>
    </div>
    <div class="well no-padding">
        @using (Html.BeginForm("Create", "TipoExercicio", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div class="control-group">
                @Html.LabelFor(model => model.dsTpExercicio, new { @class = "control-label" })
                <div class="controls">

                    @Html.EditorFor(model => model.dsTpExercicio, new { @class = "span6 m-wrap" })
                    @Html.ValidationMessageFor(model => model.dsTpExercicio)

                </div>
            </div>
            
            <div class="form-actions">
                <input type="submit" class="btn btn-success" name="enviar" value="Salvar" />
                @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
            </div>

        }
    </div>
</div>

WebFitness/Areas/Admin/Views/TipoExercicio/Edit.cshtml
@model WebFitness.TpExercicio

@{
    ViewBag.Title = "Editar";
}

<div class="span7">
    <div class="top-bar">
        <h3>
            <i class="icon-cog"></i>
            Alteração de Tipo de Exercício
        </h3>
    </div>
    <div class="well no-padding">
        @using (Html.BeginForm("Edit", "TipoExercicio", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

    
            @Html.HiddenFor(model => model.idTpExercicio)
            
            <div class="control-group">
                @Html.LabelFor(model => model.idTpExercicio, new { @class = "control-label" })
                <div class="controls">
                    @Html.EditorFor(model => model.dsTpExercicio, new { @class = "span6 m-wrap" })

                    @Html.ValidationMessageFor(model => model.dsTpExercicio)
                </div>
            </div>
            
            <div class="control-group">
                @Html.LabelFor(model => model.status, new { @class = "control-label" })

                <div class="controls">
                    <label class="radio"><span>@Html.RadioButtonFor(model => model.status, (byte) WebFitness.Status.Ativo)</span> @WebFitness.Status.Ativo</label>
                    <label class="radio"><span>@Html.RadioButtonFor(model => model.status, (byte) WebFitness.Status.Inativo)</span> @WebFitness.Status.Inativo</label>
                </div>
            </div>

            <div class="editor-field">
                @Html.HiddenFor(model => model.dtCriacao)
            </div>

            <div class="form-actions">
                <input type="submit" class="btn btn-success" name="enviar" value="Salvar" />
                @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
            </div>
        }
    </div>
</div>

WebFitness/Areas/Admin/Views/TipoExercicio/Index.cshtml
@model IEnumerable<WebFitness.TpExercicio>

@{
    ViewBag.Title = "Index";
}

<h2>Tipo de Exercício</h2>

<p>
    @Html.ActionLink("Cadastrar", "Create", null, new { @class = "btn btn-large btn-primary" })
</p>
<div class="well no-padding tab-content">
    <div class="tab-pane active" id="user-overview">
        <table class="data-table">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.idTpExercicio)</th>
                    <th>@Html.DisplayNameFor(model => model.dsTpExercicio)</th>
                    <th>@Html.DisplayNameFor(model => model.status)</th>
                    <th>@Html.DisplayNameFor(model => model.dtCriacao)</th>
                    <th class="right">Editar</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.idTpExercicio)</td>
                        <td>@Html.DisplayFor(modelItem => item.dsTpExercicio)</td>
                        <td>
                            @if (item.status == (byte)WebFitness.Status.Ativo)
                            {
                                <span class="label label-success label-height">@WebFitness.Status.Ativo</span>
                            }
                            else
                            {
                                <span class="label label-important">@WebFitness.Status.Inativo</span>
                            }

                        </td>
                        <td>@Html.DisplayFor(modelItem => item.dtCriacao)</td>
                        <td class="right">

                            @Html.ActionLink("Editar", "Edit", new { id = item.idTpExercicio }, new { @class = "btn btn-info" })

                            @if (item.status == (byte) WebFitness.Status.Ativo)
                            {
                                @Html.ActionLink("Inativar", "Inactive", new { id = item.idTpExercicio }, new { @class = "btn btn-danger" })
                            }
                            else
                            {
                                @Html.ActionLink("Ativar", "Active", new { id = item.idTpExercicio }, new { @class = "btn btn-success" })
                            }

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
