WebFitness/Areas/Admin/Controllers/ExercicioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFitness.Classes;

namespace WebFitness.Areas.Admin.Controllers
{
    public class ExercicioController : Controller
    {
        private WebfitnessDBEntities db = new WebfitnessDBEntities();
        private String controller = "Exercício";

        //
        // GET: /Admin/Exercicio/
        [Authorize]
        public ActionResult Index()
        {
            @ViewBag.Controller = controller;
            var exercicio = db.Exercicio.Include(e => e.TpExercicio);
            return View(exercicio.ToList());
        }

        //
        // GET: /Admin/Exercicio/Details/5
        [Authorize]
        public ActionResult Details(int id = 0)
        {
            @ViewBag.Controller = controller;
            Exercicio exercicio = db.Exercicio.Find(id);
            if (exercicio == null)
            {
                return HttpNotFound();
            }
            return View(exercicio);
        }

        //
        // GET: /Admin/Exercicio/Create
        [Authorize]
        public ActionResult Create()
        {
            @ViewBag.Controller = controller;
            ViewBag.idTpExercicio = new SelectList(db.TpExercicio, "idTpExercicio", "dsTpExercicio");
            return View();
        }

        //
        // POST: /Admin/Exercicio/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Exercicio exercicio)
        {
            @ViewBag.Controller = controller;
            exercicio.dtCriacao = DateTime.Now;
            exercicio.status = (byte) Status.Ativo;
            exercicio.idExercicio = 1;
            exercicio.dsExercicio = Validation.SyntaxName(exercicio.dsExercicio);
            if (ModelState.IsValid)
            {
                db.Exercicio.Add(exercicio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idTpExercicio = new SelectList(db.TpExercicio, "idTpExercicio", "dsTpExercicio", exercicio.idTpExercicio);
            return View(exercicio);
        }

        //
        // GET: /Admin/Exercicio/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            @ViewBag.Controller = controller;
            Exercicio exercicio = db.Exercicio.Find(id);
            if (exercicio == null)
            {
                return HttpNotFound();
            }
            ViewBag.idTpExercicio = new SelectList(db.TpExercicio, "idTpExercicio", "dsTpExercicio", exercicio.idTpExercicio);
            return View(exercicio);
        }

        //
        // POST: /Admin/Exercicio/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Exercicio exercicio)
        {
            @ViewBag.Controller = controller;
            if (ModelState.IsValid)
            {
                db.Entry(exercicio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idTpExercicio = new SelectList(db.TpExercicio, "idTpExercicio", "dsTpExercicio", exercicio.idTpExercicio);
            return View(exercicio);
        }

        [Authorize]
        public ActionResult Inactive(int id = 0)
        {
            @ViewBag.Controller = controller;
            Exercicio exercicio = db.Exercicio.Find(id);
            if (exercicio == null)
            {
                return HttpNotFound();
            }

            exercicio.status = (byte)Status.Inativo;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //
        // GET: /Admin/Aluno/Active/5
        [Authorize]
        public ActionResult Active(int id = 0)
        {
            @ViewBag.Controller = controller;
            Exercicio exercicio = db.Exercicio.Find(id);

            if (exercicio == null)
            {
                return HttpNotFound();
            }

            exercicio.status = (byte)Status.Ativo;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebFitness/Areas/Admin/Controllers/ManutencaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFitness.Classes;

namespace WebFitness.Areas.Admin.Controllers
{
    public class ManutencaoController : Controller
    {
        private WebfitnessDBEntities db = new WebfitnessDBEntities();
        private String controller = "Manutenção";

        //
        // GET: /Admin/Manutencao/
        [Authorize]
        public ActionResult Index()
        {
            @ViewBag.Controller = controller;
            var manutencao = db.Manutencao.Include(m => m.Equipamento).Include(m => m.Fornecedor).Include(m => m.TpManutencao);
            return View(manutencao.ToList());
        }

        //
        // GET: /Admin/Manutencao/Details/5
        [Authorize]
        public ActionResult Details(int id = 0)
        {
            @ViewBag.Controller = controller;
            Manutencao manutencao = db.Manutencao.Find(id);
            if (manutencao == null)
            {
                return HttpNotFound();
            }
            return View(manutencao);
        }

        //
        // GET: /Admin/Manutencao/Create
        [Authorize]
        public ActionResult Create()
        {
            @ViewBag.Controller = controller;
            ViewBag.idEquipamento = new SelectList(db.Equipamento, "idEquipamento", "dsEquipamento");
            ViewBag.idFornecedor = new SelectList(db.Fornecedor, "idFornecedor", "dsFornecedor");
            ViewBag.idTpManutencao = new SelectList(db.TpManutencao, "idTpManutencao", "dsTpManutencao");
            return View();
        }

        //
        // POST: /Admin/Manutencao/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Manutencao manutencao)
        {
            @ViewBag.Controller = controller;
            manutencao.idManutencao = 1;
            manutencao.dtCriacao = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Manutencao.Add(manutencao);
                db.SaveChanges();

                ContasPagar contaspagar = new ContasPagar();
                contaspagar.dsContasPagar = Validation.SyntaxName("manutenção");
                contaspagar.dtVencimento = manutencao.dtManutencao;
                contaspagar.valor = manutencao.valorManutencao;
                contaspagar.tpRegistro = (byte)TipoContasPagar.Manutencao;
                contaspagar.idTabelaFK = (from manutencaoTmp
                                            in db.Manutencao
                                        select manutencaoTmp.idManutencao).Max();
                db.ContasPagar.Add(contaspagar);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.idEquipamento = new SelectList(db.Equipamento, "idEquipamento", "dsEquipamento", manutencao.idEquipamento);
            ViewBag.idFornecedor = new SelectList(db.Fornecedor, "idFornecedor", "dsFornecedor", manutencao.idFornecedor);
            ViewBag.idTpManutencao = new SelectList(db.TpManutencao, "idTpManutencao", "dsTpManutencao", manutencao.idTpManutencao);
            return View(manutencao);
        }

        //
        // GET: /Admin/Manutencao/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            @ViewBag.Controller = controller;
            Manutencao manutencao = db.Manutencao.Find(id);
            if (manutencao == null)
            {
                return HttpNotFound();
            }
            ViewBag.idEquipamento = new SelectList(db.Equipamento, "idEquipamento", "dsEquipamento", manutencao.idEquipamento);
            ViewBag.idFornecedor = new SelectList(db.Fornecedor, "idFornecedor", "dsFornecedor", manutencao.idFornecedor);
            ViewBag.idTpManutencao = new SelectList(db.TpManutencao, "idTpManutencao", "dsTpManutencao", manutencao.idTpManutencao);
            return View(manutencao);
        }

        //
        // POST: /Admin/Manutencao/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Manutencao manutencao)
        {
            @ViewBag.Controller = controller;
            if (ModelState.IsValid)
            {
                db.Entry(manutencao).State = EntityState.Modified;
                db.SaveChanges();
                try
                {
                    ContasPagar contaspagar = (from cpgTmp
                                                 in db.ContasPagar
                                               where cpgTmp.idTabelaFK == manutencao.idManutencao
                                                  && cpgTmp.tpRegistro == (byte)TipoContasPagar.Manutencao
                                               select cpgTmp).FirstOrDefault();

                    contaspagar.valor = manutencao.valorManutencao;
                    contaspagar.dtVencimento = manutencao.dtManutencao;
                    db.Entry(contaspagar).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch { }

                return RedirectToAction("Index");
            }
            ViewBag.idEquipamento = new SelectList(db.Equipamento, "idEquipamento", "dsEquipamento", manutencao.idEquipamento);
            ViewBag.idFornecedor = new SelectList(db.Fornecedor, "idFornecedor", "dsFornecedor", manutencao.idFornecedor);
            ViewBag.idTpManutencao = new SelectList(db.TpManutencao, "idTpManutencao", "dsTpManutencao", manutencao.idTpManutencao);
            return View(manutencao);
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            @ViewBag.Controller = controller;
            Manutencao manutencao = db.Manutencao.Find(id);

            if (manutencao == null)
            {
                return HttpNotFound();
            }
            db.Manutencao.Remove(manutencao);
            db.SaveChanges();

            try
            {
                ContasPagar contaspagar = (from cpgTmp
                                                 in db.ContasPagar
                                           where cpgTmp.idTabelaFK == manutencao.idManutencao
                                              && cpgTmp.tpRegistro == (byte)TipoContasPagar.Manutencao
                                           select cpgTmp).FirstOrDefault();
                db.ContasPagar.Remove(contaspagar);
                db.SaveChanges();
            }
            catch {}

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebFitness/Areas/Admin/Controllers/TipoAulaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFitness.Classes;

namespace WebFitness.Areas.Admin.Controllers
{
    public class TipoAulaController : Controller
    {
        private WebfitnessDBEntities db = new WebfitnessDBEntities();
        private String controller = "Tipo Aula";
        //
        // GET: /Admin/TipoAula/
        [Authorize]
        public ActionResult Index()
        {
            @ViewBag.Controller = controller;
            return View(db.TpAula.ToList());
        }

        //
        // GET: /Admin/TipoAula/Create
        [Authorize]
        public ActionResult Create()
        {
            @ViewBag.Controller = controller;
            return View();
        }

        //
        // POST: /Admin/TipoAula/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TpAula tpaula)
        {

            tpaula.dsTpAula = Validation.SyntaxName(tpaula.dsTpAula);
            tpaula.dtCriacao = DateTime.Now;
            tpaula.idTpAula = 1;
            tpaula.status = (byte)Status.Ativo;

            if (ModelState.IsValid)
            {
                db.TpAula.Add(tpaula);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tpaula);
        }

        //
        // GET: /Admin/TipoAula/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            @ViewBag.Controller = controller;

            TpAula tpaula = db.TpAula.Find(id);
            if (tpaula == null)
            {
                return HttpNotFound();
            }
            return View(tpaula);
        }

        //
        // POST: /Admin/TipoAula/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TpAula tpaula)
        {
            @ViewBag.Controller = controller;
            tpaula.dsTpAula = Validation.SyntaxName(tpaula.dsTpAula);

            if (ModelState.IsValid)
            {
                db.Entry(tpaula).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tpaula);
        }

        //
        // GET: /Admin/TipoAula/Inactive/5
        [Authorize]
        public ActionResult Inactive(int id = 0)
        {
            @ViewBag.Controller = controller;

            TpAula tpaula = db.TpAula.Find(id);
            if (tpaula == null)
            {
                return HttpNotFound();
            }
            tpaula.status = (byte) Status.Inativo;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Admin/TipoAula/Active/5
        [Authorize]
        public ActionResult Active(int id = 0)
        {
            @ViewBag.Controller = controller;

            TpAula tpaula = db.TpAula.Find(id);
            if (tpaula == null)
            {
                return HttpNotFound();
            }
            tpaula.status = (byte) Status.Ativo;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebFitness/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <title>@ViewBag.Title - @ViewBag.Controller</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="~/Areas/Admin/Content/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <!-- Styles -->
    <link href="~/Content/themes/admin/base/css/chosen.css" rel="stylesheet" type="text/css">
    <link href="~/Content/themes/admin/base/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/Content/themes/admin/base/css/avocado.css" rel="stylesheet" type="text/css" id="theme-style">
    <link href="~/Content/themes/admin/base/css/prism.css" rel="stylesheet/less" type="text/css">
    <link href="~/Content/themes/admin/base/css/fullcalendar.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,600,300" rel="stylesheet" type="text/css">
    <style type="text/css">
        body {
            padding-top: 102px;
        }
    </style>
    <link href="~/Content/themes/admin/base/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="~/Content/themes/admin/admin.css" rel="stylesheet" type="text/css">

    <!-- JavaScript/jQuery, Pre-DOM -->
    <script src="~/Scripts/admin/base/jquery1.9.1.min.js"></script>
    <script src="~/Scripts/admin/base/jquery.mask.js"></script>
    <script src="~/Scripts/admin/base/admin.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>
    <script src="~/Scripts/admin/base/excanvas.min.js"></script>
    <script src="~/Scripts/admin/base/jquery.flot.js"></script>
    <script src="~/Scripts/admin/base/jquery.jpanelmenu.min.js"></script>
    <script src="~/Scripts/admin/base/jquery.cookie.js"></script>
    <script src="~/Scripts/admin/base/avocado-custom-predom.js"></script>

    <!-- HTML5, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
		<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

</head>

<body>

    <!-- Top Fixed Bar -->
    <div class="navbar navbar-inverse navbar-fixed-top">

        <!-- Top Fixed Bar: Navbar Inner -->
        <div class="navbar-inner">

            <!-- Top Fixed Bar: Container -->
            <div class="container">

                <!-- Mobile Menu Button -->
                <a href="#">
                    <button type="button" class="btn btn-navbar mobile-menu">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </a>
                <!-- / Mobile Menu Button -->

                <!-- / Logo / Brand Name -->
                <a class="brand" href="~/Admin/">Web Fitness - <b>Painel Administrativo</b></a>
                <!-- / Logo / Brand Name -->

                <!-- User Navigation -->
                <ul class="nav pull-right">
                    <!-- User Navigation: User -->
                    <li class="dropdown">

                        <!-- User Navigation: User Link -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            @{
                                @Html.Label(WebFitness.SessionManager.Funcionario.nome);
                            }
                            @*@{
                                try
                                {
                                    @Html.Label(WebFitness.Classes.SessionManager.Funcionario.nome);
                                }
                                catch
                                {
                                    Response.RedirectToRoute("LoginAdmin", "Logout");
                                }
                            }*@
                        </a>
                        <!-- / User Navigation: User Link -->

                        <!-- User Navigation: User Dropdown -->
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Logout", "Logout", "LoginAdmin")</li>
                        </ul>
                        <!-- / User Navigation: User Dropdown -->

                    </li>
                    <!-- / User Navigation: User -->

                </ul>
                <!-- / User Navigation -->

            </div>
            <!-- / Top Fixed Bar: Container -->

        </div>
        <!-- / Top Fixed Bar: Navbar Inner -->

    </div>
    <!-- / Top Fixed Bar -->

    <!-- Content Container -->
    <div class="container">

        <!-- Main Navigation: Box -->
        <div class="navbar navbar-inverse" id="nav">

            <!-- Main Navigation: Inner -->
            <div class="navbar-inner">

                <!-- Main Navigation: Nav -->
                <ul class="nav">

                    <!-- Main Navigation: Dashboard -->
                    <li class="dropdown-toggle">@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
                    <!-- / Main Navigation: Dashboard -->

                    <!-- Main Navigation: General -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-cogs"></i>Parametrizações <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Tipo Aula", "Index", "TipoAula")</li>
                            <li>@Html.ActionLink("Tipo Exercicio", "Index", "TipoExercicio")</li>
                            <li>@Html.ActionLink("Tipo Manutenção", "Index", "TipoManutencao")</li>
                        </ul>
                    </li>
                    <!-- / Main Navigation: General -->

                    <!-- Main Navigation: UI Elements -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-book"></i>Cadastros <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Aluno", "Index", "Aluno")</li>
                            <li>@Html.ActionLink("Aula", "Index", "Aula")</li>
                            <li>@Html.ActionLink("Equipamento", "Index", "Equipamento")</li>
                            <li>@Html.ActionLink("Exercício", "Index", "Exercicio")</li>
                            <li>@Html.ActionLink("Fornecedor", "Index", "Fornecedor")</li>
                            <li>@Html.ActionLink("Funcionário", "Index", "Funcionario")</li>
                            <li>@Html.ActionLink("Manutenção", "Index", "Manutencao")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-dollar"></i>Financeiro <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Contas a Pagar", "Index", "ContasPagar")</li>
                        </ul>
                    </li>

                    

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-comment"></i>Contato <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Contatos de Clietnes", "Index", "Contato")</li>
                        </ul>
                    </li>
                    <!-- / Main Navigation: UI Elements -->

                </ul>
                <!-- / Main Navigation: Nav -->


            </div>
            <!-- / Main Navigation: Inner -->

        </div>
        <!-- / Main Navigation: Box -->

        @RenderBody()

    </div>
    <!-- / Content Container -->

    <!-- Footer -->
    <footer class="footer">

        <!-- Footer Container -->
        <div class="container">

            <!-- Footer Container: Content -->
            <p>&copy; @DateTime.Now.Year - WbFitness Corporation</p>


        </div>
        <!-- / Footer Container -->

    </footer>
    <!-- / Footer -->

</body>

<!-- Javascript
	    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="~/Scripts/admin/base/jquery.hotkeys.js"></script>
<script src="~/Scripts/admin/base/fullcalendar.min.js"></script>
<script src="~/Scripts/admin/base/jquery-ui-1.10.2.custom.min.js"></script>
<script src="~/Scripts/admin/base/jquery.pajinate.js"></script>
<script src="~/Scripts/admin/base/jquery.prism.min.js"></script>
<script src="~/Scripts/admin/base/jquery.dataTables.min.js"></script>
<script src="~/Scripts/admin/base/jquery.flot.time.js"></script>
<script src="~/Scripts/admin/base/jquery.flot.pie.js"></script>
<script src="~/Scripts/admin/base/jquery.flot.resize.js"></script>
<script src="~/Scripts/admin/base/bootstrap.min.js"></script>
<script src="~/Scripts/admin/base/bootstrap-wysiwyg.js"></script>
<script src="~/Scripts/admin/base/bootstrap-typeahead.js"></script>
<script src="~/Scripts/admin/base/jquery.easing.min.js"></script>
<script src="~/Scripts/admin/base/jquery.chosen.min.js"></script>
<script src="~/Scripts/admin/base/avocado-custom.js"></script>

</html>