WebFitness/Areas/Admin/Controllers/ContasPagarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFitness.Classes;

namespace WebFitness.Areas.Admin
{
    public class ContasPagarController : Controller
    {
        private WebfitnessDBEntities db = new WebfitnessDBEntities();

        //
        // GET: /Admin/ContasPagar/

        public ActionResult Index()
        {
            return View(db.ContasPagar.ToList());
        }

        //
        // GET: /Admin/ContasPagar/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Admin/ContasPagar/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContasPagar contaspagar)
        {
            contaspagar.idContasPagar = 1;
            contaspagar.tpRegistro = (byte) TipoContasPagar.Diversas;
            contaspagar.dsContasPagar = Validation.SyntaxName(contaspagar.dsContasPagar);

            if (ModelState.IsValid)
            {
                db.ContasPagar.Add(contaspagar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contaspagar);
        }

        //
        // GET: /Admin/ContasPagar/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ContasPagar contaspagar = db.ContasPagar.Find(id);
            if (contaspagar == null)
            {
                return HttpNotFound();
            }
            return View(contaspagar);
        }

        //
        // POST: /Admin/ContasPagar/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ContasPagar contaspagar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contaspagar).State = EntityState.Modified;
                db.SaveChanges();

                if ( contaspagar.tpRegistro == (byte) TipoContasPagar.Manutencao) 
                {
                    try
                    {
                        Manutencao manutencao = db.Manutencao.Find(contaspagar.idTabelaFK);
                        manutencao.valorManutencao = contaspagar.valor;
                        db.Entry(manutencao).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    catch { }
                }
                else if (contaspagar.tpRegistro == (byte)TipoContasPagar.Salario)
                {

                }
                return RedirectToAction("Index");
            }
            return View(contaspagar);
        }

        //
        // GET: /Admin/ContasPagar/Delete/5

        public ActionResult Delete(int id = 0)
        {
            ContasPagar contaspagar = db.ContasPagar.Find(id);
            if (contaspagar == null)
            {
                return HttpNotFound();
            }
            return View(contaspagar);
        }

        //
        // POST: /Admin/ContasPagar/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ContasPagar contaspagar = db.ContasPagar.Find(id);
            db.ContasPagar.Remove(contaspagar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebFitness/Areas/Admin/Views/ContasPagar/Create.cshtml
@model WebFitness.ContasPagar

@{
    ViewBag.Title = "Cadastrar";
}

<div class="span7">
    <div class="top-bar">
        <h3>
            <i class="icon-cog"></i>
            Cadastro de Contas a Pagar
        </h3>
    </div>
    <div class="well no-padding">

        @using (Html.BeginForm("Create", "ContasPagar", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div class="control-group">
                @Html.LabelFor(model => model.dsContasPagar, new { @class = "control-label" })

                <div class="controls">
                    @Html.EditorFor(model => model.dsContasPagar, new { @class = "span6 m-wrap" })
                    @Html.ValidationMessageFor(model => model.dsContasPagar)
                </div>
            </div>
            
            <div class="control-group">
                @Html.LabelFor(model => model.valor, new { @class = "control-label" })

                <div class="controls">
                    @Html.EditorFor(model => model.valor, new { @class = "span6 m-wrap" })
                    @Html.ValidationMessageFor(model => model.valor)
                </div>
            </div>
            
            <div class="control-group">
                @Html.LabelFor(model => model.dtVencimento, new { @class = "control-label" })

                <div class="controls">
                    @Html.EditorFor(model => model.dtVencimento, new { @class = "span6 m-wrap" })
                    @Html.ValidationMessageFor(model => model.dtVencimento)
                </div>
            </div>
            
            <div class="control-group">
                @Html.LabelFor(model => model.dtPagamento, new { @class = "control-label" })

                <div class="controls">
                    @Html.EditorFor(model => model.dtPagamento, new { @class = "span6 m-wrap" })
                    @Html.ValidationMessageFor(model => model.dtPagamento)
                </div>
            </div>
            
            <div class="form-actions">
                <input type="submit" class="btn btn-success" name="enviar" value="Salvar" />
                @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
            </div>


        }

    </div>
</div>

WebFitness/Areas/Admin/Views/ContasPagar/Edit.cshtml
@model WebFitness.ContasPagar

@{
    ViewBag.Title = "Editar";
}

<div class="span7">
    <div class="top-bar">
        <h3>
            <i class="icon-cog"></i>
            Cadastro de Contas a Pagar
        </h3>
    </div>
    <div class="well no-padding">

        @using (Html.BeginForm("Edit", "ContasPagar", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            @Html.HiddenFor(model => model.idContasPagar)
            @Html.HiddenFor(model => model.idTabelaFK)
            @Html.HiddenFor(model => model.tpRegistro)


            <div class="control-group">
                @Html.LabelFor(model => model.dsContasPagar, new { @class = "control-label" })

                <div class="controls">
                    @Html.EditorFor(model => model.dsContasPagar, new { @class = "span6 m-wrap" })
                    @Html.ValidationMessageFor(model => model.dsContasPagar)
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.valor, new { @class = "control-label" })

                <div class="controls">
                    @Html.EditorFor(model => model.valor, new { @class = "span6 m-wrap" })
                    @Html.ValidationMessageFor(model => model.valor)
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.dtVencimento, new { @class = "control-label" })

                <div class="controls">
                    @Html.EditorFor(model => model.dtVencimento, new { @class = "span6 m-wrap" })
                    @Html.ValidationMessageFor(model => model.dtVencimento)
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.dtPagamento, new { @class = "control-label" })

                <div class="controls">
                    @Html.EditorFor(model => model.dtPagamento, new { @class = "span6 m-wrap" })
                    @Html.ValidationMessageFor(model => model.dtPagamento)
                </div>
            </div>

            <div class="form-actions">
                <input type="submit" class="btn btn-success" name="enviar" value="Salvar" />
                @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
            </div>

        }

    </div>
</div>

WebFitness/Areas/Admin/Views/ContasPagar/Index.cshtml
@model IEnumerable<WebFitness.ContasPagar>

@{
    ViewBag.Title = "Index";
}

<h2>Contas a Pagar</h2>

<p>
    @Html.ActionLink("Cadastrar", "Create", null, new { @class = "btn btn-large btn-primary" })
</p>

<div class="well no-padding tab-content">
    <div class="tab-pane active" id="user-overview">
        <table class="data-table">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.dsContasPagar)</th>
                    <th>@Html.DisplayNameFor(model => model.valor)</th>
                    <th>@Html.DisplayNameFor(model => model.dtVencimento)</th>
                    <th>@Html.DisplayNameFor(model => model.dtPagamento)</th>
                    <th>@Html.DisplayNameFor(model => model.tpRegistro)</th>
                    <th class="right"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.dsContasPagar)</td>
                        <td>@Html.DisplayFor(modelItem => item.valor)</td>
                        <td>@Html.DisplayFor(modelItem => item.dtVencimento)</td>
                        <td>@Html.DisplayFor(modelItem => item.dtPagamento)</td>
                        <td>@if( item.tpRegistro == (byte) WebFitness.TipoContasPagar.Diversas)
                            {
                                @WebFitness.TipoContasPagar.Diversas
                            }
                            else if (item.tpRegistro == (byte)WebFitness.TipoContasPagar.Manutencao)
                            {
                                @WebFitness.TipoContasPagar.Manutencao
                            }else
                            {
                                @WebFitness.TipoContasPagar.Salario
                            }
                        </td>
                        <td class="right">
                            @Html.ActionLink("Editar", "Edit", new { id = item.idContasPagar }, new { @class = "btn btn-info" })
                            @Html.ActionLink("Excluir", "Delete", new { id = item.idContasPagar }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>